# Data Wrangling for: Udacity Project - Explanatory Data Analysis with Tableau

Author: Shawn Gong

Date: 6th June 2018

## Questions to ask

1. What occupations receive high credit rating?
2. Which states receives higher rating?
3. How does owning a home affect the credit rating of a loan borrower?
4. How do the openings of credit line affect the credit rating?
5. How do the recommendations affect?
6. How does monthly payment associate with occupation?
7. Stated monthly income of different states.
8. How does stated monthly income affect the amount of loan.
9. Debt to income ratio of different states.
10. Custom risk score compare to 
	1. occupation
	2. Stated monthly income
	3. Total credit line
11. Listing creation date vs. Credit score
12. Interest rate vs.
	1. Credit score
	2. Monthly income
13. How do the interest rates change for different kinds of debt these years.
14. What kind of loan is most popular in different years?
15. What occupation tends to default or charge off or default a loan? What about income?
16. What income level is most likely to default a loan?
17. What state mostly likely to default a loan?

## Assess the data set

In [1]:
## import necessary libraries
import pandas as pd
import numpy as np

In [2]:
df_loan = pd.read_csv('prosperLoanData.csv')

In [3]:
df_loan.head()

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,...,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
0,1021339766868145413AB3B,193129,2007-08-26 19:09:29.263000000,C,36,Completed,2009-08-14 00:00:00,0.16516,0.1580,0.1380,...,-133.18,0.0,0.0,0.0,0.0,1.0,0,0,0.0,258
1,10273602499503308B223C1,1209647,2014-02-27 08:28:07.900000000,NaN,36,Current,NaN,0.12016,0.0920,0.0820,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
2,0EE9337825851032864889A,81716,2007-01-05 15:00:47.090000000,HR,36,Completed,2009-12-17 00:00:00,0.28269,0.2750,0.2400,...,-24.20,0.0,0.0,0.0,0.0,1.0,0,0,0.0,41
3,0EF5356002482715299901A,658116,2012-10-22 11:02:35.010000000,NaN,36,Current,NaN,0.12528,0.0974,0.0874,...,-108.01,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
4,0F023589499656230C5E3E2,909464,2013-09-14 18:38:39.097000000,NaN,36,Current,NaN,0.24614,0.2085,0.1985,...,-60.27,0.0,0.0,0.0,0.0,1.0,0,0,0.0,20

In [4]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 81 columns):
ListingKey                             113937 non-null object
ListingNumber                          113937 non-null int64
ListingCreationDate                    113937 non-null object
CreditGrade                            28953 non-null object
Term                                   113937 non-null int64
LoanStatus                             113937 non-null object
ClosedDate                             55089 non-null object
BorrowerAPR                            113912 non-null float64
BorrowerRate                           113937 non-null float64
LenderYield                            113937 non-null float64
EstimatedEffectiveYield                84853 non-null float64
EstimatedLoss                          84853 non-null float64
EstimatedReturn                        84853 non-null float64
ProsperRating (numeric)                84853 non-null float64
ProsperRating (Alpha)                  84853 non-null object
ProsperScore                           84853 non-null float64
ListingCategory (numeric)              113937 non-null int64
BorrowerState                          108422 non-null object
Occupation                             110349 non-null object
EmploymentStatus                       111682 non-null object
EmploymentStatusDuration               106312 non-null float64
IsBorrowerHomeowner                    113937 non-null bool
CurrentlyInGroup                       113937 non-null bool
GroupKey                               13341 non-null object
DateCreditPulled                       113937 non-null object
CreditScoreRangeLower                  113346 non-null float64
CreditScoreRangeUpper                  113346 non-null float64
FirstRecordedCreditLine                113240 non-null object
CurrentCreditLines                     106333 non-null float64
OpenCreditLines                        106333 non-null float64
TotalCreditLinespast7years             113240 non-null float64
OpenRevolvingAccounts                  113937 non-null int64
OpenRevolvingMonthlyPayment            113937 non-null float64
InquiriesLast6Months                   113240 non-null float64
TotalInquiries                         112778 non-null float64
CurrentDelinquencies                   113240 non-null float64
AmountDelinquent                       106315 non-null float64
DelinquenciesLast7Years                112947 non-null float64
PublicRecordsLast10Years               113240 non-null float64
PublicRecordsLast12Months              106333 non-null float64
RevolvingCreditBalance                 106333 non-null float64
BankcardUtilization                    106333 non-null float64
AvailableBankcardCredit                106393 non-null float64
TotalTrades                            106393 non-null float64
TradesNeverDelinquent (percentage)     106393 non-null float64
TradesOpenedLast6Months                106393 non-null float64
DebtToIncomeRatio                      105383 non-null float64
IncomeRange                            113937 non-null object
IncomeVerifiable                       113937 non-null bool
StatedMonthlyIncome                    113937 non-null float64
LoanKey                                113937 non-null object
TotalProsperLoans                      22085 non-null float64
TotalProsperPaymentsBilled             22085 non-null float64
OnTimeProsperPayments                  22085 non-null float64
ProsperPaymentsLessThanOneMonthLate    22085 non-null float64
ProsperPaymentsOneMonthPlusLate        22085 non-null float64
ProsperPrincipalBorrowed               22085 non-null float64
ProsperPrincipalOutstanding            22085 non-null float64
ScorexChangeAtTimeOfListing            18928 non-null float64
LoanCurrentDaysDelinquent              113937 non-null int64
LoanFirstDefaultedCycleNumber          16952 non-null float64
LoanMonthsSinceOrigination             113937 non-null int64
LoanNumber                             113937 non-null int64
LoanOriginalAmount                     113937 non-null int64
LoanOriginationDate                    113937 non-null object
LoanOriginationQuarter                 113937 non-null object
MemberKey                              113937 non-null object
MonthlyLoanPayment                     113937 non-null float64
LP_CustomerPayments                    113937 non-null float64
LP_CustomerPrincipalPayments           113937 non-null float64
LP_InterestandFees                     113937 non-null float64
LP_ServiceFees                         113937 non-null float64
LP_CollectionFees                      113937 non-null float64
LP_GrossPrincipalLoss                  113937 non-null float64
LP_NetPrincipalLoss                    113937 non-null float64
LP_NonPrincipalRecoverypayments        113937 non-null float64
PercentFunded                          113937 non-null float64
Recommendations                        113937 non-null int64
InvestmentFromFriendsCount             113937 non-null int64
InvestmentFromFriendsAmount            113937 non-null float64
Investors                              113937 non-null int64
dtypes: bool(3), float64(50), int64(11), object(17)
memory usage: 68.1+ MB

In [5]:
df_loan[df_loan.duplicated('ListingKey', keep = False)].sort_values('ListingKey')

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,...,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
32680,00223594917038064A7C947,998257,2013-11-15 16:58:37.167000000,NaN,36,Current,NaN,0.23540,0.1980,0.1880,...,-12.34,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
32681,00223594917038064A7C947,998257,2013-11-15 16:58:37.167000000,NaN,36,Current,NaN,0.23540,0.1980,0.1880,...,-12.34,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
32964,00473590513960687DD308F,941296,2013-10-07 15:47:36.023000000,NaN,60,Current,NaN,0.22242,0.1980,0.1880,...,-73.12,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
17274,00473590513960687DD308F,941296,2013-10-07 15:47:36.023000000,NaN,60,Current,NaN,0.22242,0.1980,0.1880,...,-73.12,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
7478,0098360461900952056DB93,1190614,2014-03-02 14:21:39.583000000,NaN,36,Current,NaN,0.29660,0.2574,0.2474,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
33220,0098360461900952056DB93,1190614,2014-03-02 14:21:39.583000000,NaN,36,Current,NaN,0.29660,0.2574,0.2474,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
27677,01163604029146842E28D9C,1233732,2014-02-25 14:33:39.830000000,NaN,36,Current,NaN,0.31975,0.2800,0.2700,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
788,01163604029146842E28D9C,1233732,2014-02-25 14:33:39.830000000,NaN,36,Current,NaN,0.31975,0.2800,0.2700,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
27360,014F35910923350802E1B29,930618,2013-09-26 16:44:24.163000000,NaN,60,Current,NaN,0.19323,0.1695,0.1595,...,-27.50,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
18324,014F35910923350802E1B29,930618,2013-09-26 16:44:24.163000000,NaN,60,Current,NaN,0.19323,0.1695,0.1595,...,-27.50,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
18849,018A360063948152589C8BE,1136886,2014-01-14 07:56:29.517000000,NaN,60,Completed,2014-02-24 00:00:00,0.28875,0.2624,0.2524,...,-1.66,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
33959,018A360063948152589C8BE,1136886,2014-01-14 07:56:29.517000000,NaN,60,Completed,2014-02-24 00:00:00,0.28875,0.2624,0.2524,...,-1.66,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
7555,021F3593082999771F5E621,970570,2013-11-01 13:53:22,NaN,36,Current,NaN,0.12691,0.0990,0.0890,...,-16.78,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
1296,021F3593082999771F5E621,970570,2013-11-01 13:53:22,NaN,36,Current,NaN,0.12691,0.0990,0.0890,...,-16.78,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
19256,02AD3598720043943A56991,1097279,2013-12-26 13:26:46.030000000,NaN,36,Current,NaN,0.23375,0.1960,0.1860,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,57
9460,02AD3598720043943A56991,1097279,2013-12-26 13:26:46.030000000,NaN,36,Current,NaN,0.23375,0.1960,0.1860,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,57
36511,04053588643952074304508,902157,2013-09-13 22:32:56.560000000,NaN,36,Current,NaN,0.27285,0.2346,0.2246,...,-15.92,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
21839,04053588643952074304508,902157,2013-09-13 22:32:56.560000000,NaN,36,Current,NaN,0.27285,0.2346,0.2246,...,-15.92,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
11889,04A53597159795718CE3A26,1063352,2013-12-09 18:54:29.140000000,NaN,36,Current,NaN,0.15223,0.1239,0.1139,...,-7.43,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
11888,04A53597159795718CE3A26,1063352,2013-12-09 18:54:29.140000000,NaN,36,Current,NaN,0.15223,0.1239,0.1139,...,-7.43,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
66386,04C13599434217079754AEE,1102061,2013-12-29 18:39:22.483000000,NaN,36,Current,NaN,0.09469,0.0809,0.0709,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
11400,04C13599434217079754AEE,1102061,2013-12-29 18:39:22.483000000,NaN,36,Current,NaN,0.09469,0.0809,0.0709,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
21845,04C13599434217079754AEE,1102061,2013-12-29 18:39:22.483000000,NaN,36,Current,NaN,0.09469,0.0809,0.0709,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
11117,05043603291539396A9E43E,1184734,2014-02-26 09:15:42.277000000,NaN,60,Current,NaN,0.19553,0.1715,0.1615,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,49
22452,05043603291539396A9E43E,1184734,2014-02-26 09:15:42.277000000,NaN,60,Current,NaN,0.19553,0.1715,0.1615,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,49
12956,059135904162159071EA963,925803,2013-09-26 06:08:44.510000000,NaN,36,Current,NaN,0.23540,0.1980,0.1880,...,-19.74,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
3422,059135904162159071EA963,925803,2013-09-26 06:08:44.510000000,NaN,36,Current,NaN,0.23540,0.1980,0.1880,...,-19.74,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
3424,05973602960011656FA5D4E,1188772,2014-03-01 17:24:57.483000000,NaN,36,Current,NaN,0.13734,0.1089,0.0989,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
67648,05973602960011656FA5D4E,1188772,2014-03-01 17:24:57.483000000,NaN,36,Current,NaN,0.13734,0.1089,0.0989,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
4270,05E135934278258503421EB,989195,2013-11-02 14:11:49.110000000,NaN,36,Current,NaN,0.32446,0.2850,0.2750,...,-6.36,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47709,FC453601437434724612543,1154037,2014-01-22 05:36:40.333000000,NaN,36,Current,NaN,0.30172,0.2624,0.2524,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
53552,FC5F3592110384244FC7BA7,961598,2013-10-17 19:00:53.250000000,NaN,60,Current,NaN,0.20321,0.1790,0.1690,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
27266,FC5F3592110384244FC7BA7,961598,2013-10-17 19:00:53.250000000,NaN,60,Current,NaN,0.20321,0.1790,0.1690,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
33975,FC5F3592110384244FC7BA7,961598,2013-10-17 19:00:53.250000000,NaN,60,Current,NaN,0.20321,0.1790,0.1690,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
54843,FC8F359832109202000D82C,1119803,2014-01-08 14:09:14.177000000,NaN,60,Current,NaN,0.13227,0.1099,0.0999,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
53655,FC8F359832109202000D82C,1119803,2014-01-08 14:09:14.177000000,NaN,60,Current,NaN,0.13227,0.1099,0.0999,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
52210,FCF635931956615326179DF,959753,2013-10-17 12:01:59.453000000,NaN,36,Current,NaN,0.12691,0.0990,0.0890,...,-36.86,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
64316,FCF635931956615326179DF,959753,2013-10-17 12:01:59.453000000,NaN,36,Current,NaN,0.12691,0.0990,0.0890,...,-36.86,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
72331,FD143593949672534EF3594,977573,2013-10-28 23:04:25.740000000,NaN,36,Current,NaN,0.24205,0.2045,0.1945,...,-37.03,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
53669,FD143593949672534EF3594,977573,2013-10-28 23:04:25.740000000,NaN,36,Current,NaN,0.24205,0.2045,0.1945,...,-37.03,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
18636,FD4F359960143939223E9C0,1078459,2014-01-03 09:32:03.783000000,NaN,36,Current,NaN,0.28636,0.2474,0.2374,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
76889,FD4F359960143939223E9C0,1078459,2014-01-03 09:32:03.783000000,NaN,36,Current,NaN,0.28636,0.2474,0.2374,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
68778,FD6335903636172174A3837,899188,2013-09-16 14:35:55.227000000,NaN,60,Current,NaN,0.17839,0.1550,0.1450,...,-47.11,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
68779,FD6335903636172174A3837,899188,2013-09-16 14:35:55.227000000,NaN,60,Current,NaN,0.17839,0.1550,0.1450,...,-47.11,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
59758,FD8535964303574380588AC,1046027,2013-12-03 10:57:46.427000000,NaN,36,Current,NaN,0.31668,0.2774,0.2674,...,-8.42,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
36573,FD8535964303574380588AC,1046027,2013-12-03 10:57:46.427000000,NaN,36,Current,NaN,0.31668,0.2774,0.2674,...,-8.42,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
48517,FD9D359492836040450E61D,1060452,2013-11-27 14:20:29.743000000,NaN,60,Current,NaN,0.13227,0.1099,0.0999,...,-25.32,0.0,0.0,0.0,0.0,1.0,0,0,0.0,214
69553,FD9D359492836040450E61D,1060452,2013-11-27 14:20:29.743000000,NaN,60,Current,NaN,0.13227,0.1099,0.0999,...,-25.32,0.0,0.0,0.0,0.0,1.0,0,0,0.0,214
55130,FDCB3592503114504DA2C65,981333,2013-10-15 08:57:16.180000000,NaN,36,Current,NaN,0.19501,0.1585,0.1485,...,-51.56,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
53968,FDCB3592503114504DA2C65,981333,2013-10-15 08:57:16.180000000,NaN,36,Current,NaN,0.19501,0.1585,0.1485,...,-51.56,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
93034,FE7436021001476584CACCD,1191338,2014-02-13 11:49:22.950000000,NaN,36,Current,NaN,0.22812,0.1905,0.1805,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,67
32846,FE7436021001476584CACCD,1191338,2014-02-13 11:49:22.950000000,NaN,36,Current,NaN,0.22812,0.1905,0.1805,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,67
73529,FED53589115301546EB2BEB,907826,2013-09-14 13:17:16.497000000,NaN,36,Current,NaN,0.15324,0.1249,0.1149,...,-9.85,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
79541,FED53589115301546EB2BEB,907826,2013-09-14 13:17:16.497000000,NaN,36,Current,NaN,0.15324,0.1249,0.1149,...,-9.85,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
80321,FEF9358974260956441C450,906461,2013-09-14 09:32:49.973000000,NaN,36,Current,NaN,0.21699,0.1800,0.1700,...,-8.64,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
48533,FEF9358974260956441C450,906461,2013-09-14 09:32:49.973000000,NaN,36,Current,NaN,0.21699,0.1800,0.1700,...,-8.64,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
73622,FF1B3590569175597E6830C,935199,2013-09-28 08:14:30.190000000,NaN,36,Current,NaN,0.15833,0.1299,0.1199,...,-8.14,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
73623,FF1B3590569175597E6830C,935199,2013-09-28 08:14:30.190000000,NaN,36,Current,NaN,0.15833,0.1299,0.1199,...,-8.14,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
57066,FFE13600149501913291BF7,1122473,2014-01-09 10:59:42.003000000,NaN,36,Current,NaN,0.29455,0.2554,0.2454,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
58306,FFE13600149501913291BF7,1122473,2014-01-09 10:59:42.003000000,NaN,36,Current,NaN,0.29455,0.2554,0.2454,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1

In [6]:
df_loan.CreditGrade.unique()

array(['C', nan, 'HR', 'AA', 'D', 'B', 'E', 'A', 'NC'], dtype=object)

## Issues

Quality:
* Based on the question we have for this dataset, there are many variables we don't think would be valuable for the analysis. 
* There are duplicated observations.

Tidiness:
* The prosper rating and credit grade variable describe the same thing but are seperated based on date of the loan being created.

## Cleaning

### Drop Duplicated observations

In [7]:
df_loan.drop_duplicates('ListingKey', inplace = True)

In [8]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113066 entries, 0 to 113936
Data columns (total 81 columns):
ListingKey                             113066 non-null object
ListingNumber                          113066 non-null int64
ListingCreationDate                    113066 non-null object
CreditGrade                            28953 non-null object
Term                                   113066 non-null int64
LoanStatus                             113066 non-null object
ClosedDate                             55076 non-null object
BorrowerAPR                            113041 non-null float64
BorrowerRate                           113066 non-null float64
LenderYield                            113066 non-null float64
EstimatedEffectiveYield                83982 non-null float64
EstimatedLoss                          83982 non-null float64
EstimatedReturn                        83982 non-null float64
ProsperRating (numeric)                83982 non-null float64
ProsperRating (Alpha)                  83982 non-null object
ProsperScore                           83982 non-null float64
ListingCategory (numeric)              113066 non-null int64
BorrowerState                          107551 non-null object
Occupation                             109537 non-null object
EmploymentStatus                       110811 non-null object
EmploymentStatusDuration               105441 non-null float64
IsBorrowerHomeowner                    113066 non-null bool
CurrentlyInGroup                       113066 non-null bool
GroupKey                               13339 non-null object
DateCreditPulled                       113066 non-null object
CreditScoreRangeLower                  112475 non-null float64
CreditScoreRangeUpper                  112475 non-null float64
FirstRecordedCreditLine                112369 non-null object
CurrentCreditLines                     105462 non-null float64
OpenCreditLines                        105462 non-null float64
TotalCreditLinespast7years             112369 non-null float64
OpenRevolvingAccounts                  113066 non-null int64
OpenRevolvingMonthlyPayment            113066 non-null float64
InquiriesLast6Months                   112369 non-null float64
TotalInquiries                         111907 non-null float64
CurrentDelinquencies                   112369 non-null float64
AmountDelinquent                       105444 non-null float64
DelinquenciesLast7Years                112076 non-null float64
PublicRecordsLast10Years               112369 non-null float64
PublicRecordsLast12Months              105462 non-null float64
RevolvingCreditBalance                 105462 non-null float64
BankcardUtilization                    105462 non-null float64
AvailableBankcardCredit                105522 non-null float64
TotalTrades                            105522 non-null float64
TradesNeverDelinquent (percentage)     105522 non-null float64
TradesOpenedLast6Months                105522 non-null float64
DebtToIncomeRatio                      104594 non-null float64
IncomeRange                            113066 non-null object
IncomeVerifiable                       113066 non-null bool
StatedMonthlyIncome                    113066 non-null float64
LoanKey                                113066 non-null object
TotalProsperLoans                      21923 non-null float64
TotalProsperPaymentsBilled             21923 non-null float64
OnTimeProsperPayments                  21923 non-null float64
ProsperPaymentsLessThanOneMonthLate    21923 non-null float64
ProsperPaymentsOneMonthPlusLate        21923 non-null float64
ProsperPrincipalBorrowed               21923 non-null float64
ProsperPrincipalOutstanding            21923 non-null float64
ScorexChangeAtTimeOfListing            18912 non-null float64
LoanCurrentDaysDelinquent              113066 non-null int64
LoanFirstDefaultedCycleNumber          16952 non-null float64
LoanMonthsSinceOrigination             113066 non-null int64
LoanNumber                             113066 non-null int64
LoanOriginalAmount                     113066 non-null int64
LoanOriginationDate                    113066 non-null object
LoanOriginationQuarter                 113066 non-null object
MemberKey                              113066 non-null object
MonthlyLoanPayment                     113066 non-null float64
LP_CustomerPayments                    113066 non-null float64
LP_CustomerPrincipalPayments           113066 non-null float64
LP_InterestandFees                     113066 non-null float64
LP_ServiceFees                         113066 non-null float64
LP_CollectionFees                      113066 non-null float64
LP_GrossPrincipalLoss                  113066 non-null float64
LP_NetPrincipalLoss                    113066 non-null float64
LP_NonPrincipalRecoverypayments        113066 non-null float64
PercentFunded                          113066 non-null float64
Recommendations                        113066 non-null int64
InvestmentFromFriendsCount             113066 non-null int64
InvestmentFromFriendsAmount            113066 non-null float64
Investors                              113066 non-null int64
dtypes: bool(3), float64(50), int64(11), object(17)
memory usage: 68.5+ MB

### Drop unnecessary variables

In [9]:
unnecessary_variables = ['ListingNumber', 'ClosedDate', 'LenderYield', 
                         'EstimatedEffectiveYield', 'EstimatedLoss', 
                         'EstimatedReturn', 'EmploymentStatusDuration',
                         'CurrentlyInGroup', 'GroupKey', 'DateCreditPulled',
                         'FirstRecordedCreditLine', 'CurrentCreditLines', 'TotalCreditLinespast7years',
                         'OpenRevolvingAccounts', 'OpenRevolvingMonthlyPayment', 'TotalInquiries', 
                         'CurrentDelinquencies', 'DelinquenciesLast7Years', 'PublicRecordsLast10Years',
                         'PublicRecordsLast12Months', 'TotalTrades', 'TradesNeverDelinquent (percentage)',
                         'TradesOpenedLast6Months', 'LoanKey', 'TotalProsperLoans', 'TotalProsperPaymentsBilled',
                         'OnTimeProsperPayments', 'ProsperPaymentsLessThanOneMonthLate',
                         'ProsperPaymentsOneMonthPlusLate', 'ProsperPrincipalBorrowed', 'ProsperPrincipalOutstanding',
                         'ScorexChangeAtTimeOfListing', 'LoanCurrentDaysDelinquent', 'LoanFirstDefaultedCycleNumber',
                         'LoanMonthsSinceOrigination', 'LoanNumber', 'LoanOriginationDate', 'LoanOriginationQuarter', 
                         'MemberKey', 'LP_CustomerPayments', 'LP_CustomerPrincipalPayments', 'LP_InterestandFees', 
                         'LP_ServiceFees', 'LP_CollectionFees', 'LP_GrossPrincipalLoss', 'LP_NetPrincipalLoss', 
                         'LP_NonPrincipalRecoverypayments', 'InvestmentFromFriendsCount', 'InvestmentFromFriendsAmount']

In [10]:
df_loan.drop(unnecessary_variables, axis = 1, inplace = True)

In [11]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113066 entries, 0 to 113936
Data columns (total 32 columns):
ListingKey                   113066 non-null object
ListingCreationDate          113066 non-null object
CreditGrade                  28953 non-null object
Term                         113066 non-null int64
LoanStatus                   113066 non-null object
BorrowerAPR                  113041 non-null float64
BorrowerRate                 113066 non-null float64
ProsperRating (numeric)      83982 non-null float64
ProsperRating (Alpha)        83982 non-null object
ProsperScore                 83982 non-null float64
ListingCategory (numeric)    113066 non-null int64
BorrowerState                107551 non-null object
Occupation                   109537 non-null object
EmploymentStatus             110811 non-null object
IsBorrowerHomeowner          113066 non-null bool
CreditScoreRangeLower        112475 non-null float64
CreditScoreRangeUpper        112475 non-null float64
OpenCreditLines              105462 non-null float64
InquiriesLast6Months         112369 non-null float64
AmountDelinquent             105444 non-null float64
RevolvingCreditBalance       105462 non-null float64
BankcardUtilization          105462 non-null float64
AvailableBankcardCredit      105522 non-null float64
DebtToIncomeRatio            104594 non-null float64
IncomeRange                  113066 non-null object
IncomeVerifiable             113066 non-null bool
StatedMonthlyIncome          113066 non-null float64
LoanOriginalAmount           113066 non-null int64
MonthlyLoanPayment           113066 non-null float64
PercentFunded                113066 non-null float64
Recommendations              113066 non-null int64
Investors                    113066 non-null int64
dtypes: bool(2), float64(16), int64(5), object(9)
memory usage: 27.0+ MB

In [12]:
credit_rating = pd.concat([df_loan['CreditGrade'].dropna(), df_loan['ProsperRating (Alpha)'].dropna()]).sort_index()

In [13]:
df_loan = pd.merge(df_loan, pd.DataFrame(credit_rating), how = 'outer', left_index = True, right_index = True)

In [14]:
df_loan.rename(columns = {0: 'CreditRating'}, inplace = True)

In [15]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113066 entries, 0 to 113936
Data columns (total 33 columns):
ListingKey                   113066 non-null object
ListingCreationDate          113066 non-null object
CreditGrade                  28953 non-null object
Term                         113066 non-null int64
LoanStatus                   113066 non-null object
BorrowerAPR                  113041 non-null float64
BorrowerRate                 113066 non-null float64
ProsperRating (numeric)      83982 non-null float64
ProsperRating (Alpha)        83982 non-null object
ProsperScore                 83982 non-null float64
ListingCategory (numeric)    113066 non-null int64
BorrowerState                107551 non-null object
Occupation                   109537 non-null object
EmploymentStatus             110811 non-null object
IsBorrowerHomeowner          113066 non-null bool
CreditScoreRangeLower        112475 non-null float64
CreditScoreRangeUpper        112475 non-null float64
OpenCreditLines              105462 non-null float64
InquiriesLast6Months         112369 non-null float64
AmountDelinquent             105444 non-null float64
RevolvingCreditBalance       105462 non-null float64
BankcardUtilization          105462 non-null float64
AvailableBankcardCredit      105522 non-null float64
DebtToIncomeRatio            104594 non-null float64
IncomeRange                  113066 non-null object
IncomeVerifiable             113066 non-null bool
StatedMonthlyIncome          113066 non-null float64
LoanOriginalAmount           113066 non-null int64
MonthlyLoanPayment           113066 non-null float64
PercentFunded                113066 non-null float64
Recommendations              113066 non-null int64
Investors                    113066 non-null int64
CreditRating                 112935 non-null object
dtypes: bool(2), float64(16), int64(5), object(10)
memory usage: 27.8+ MB

### Drop any NaN value in the credit rating variable

In [16]:
df_loan.dropna(subset = ['CreditRating'], inplace = True)

In [17]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112935 entries, 0 to 113936
Data columns (total 33 columns):
ListingKey                   112935 non-null object
ListingCreationDate          112935 non-null object
CreditGrade                  28953 non-null object
Term                         112935 non-null int64
LoanStatus                   112935 non-null object
BorrowerAPR                  112910 non-null float64
BorrowerRate                 112935 non-null float64
ProsperRating (numeric)      83982 non-null float64
ProsperRating (Alpha)        83982 non-null object
ProsperScore                 83982 non-null float64
ListingCategory (numeric)    112935 non-null int64
BorrowerState                107420 non-null object
Occupation                   109406 non-null object
EmploymentStatus             110680 non-null object
IsBorrowerHomeowner          112935 non-null bool
CreditScoreRangeLower        112344 non-null float64
CreditScoreRangeUpper        112344 non-null float64
OpenCreditLines              105331 non-null float64
InquiriesLast6Months         112238 non-null float64
AmountDelinquent             105313 non-null float64
RevolvingCreditBalance       105331 non-null float64
BankcardUtilization          105331 non-null float64
AvailableBankcardCredit      105391 non-null float64
DebtToIncomeRatio            104474 non-null float64
IncomeRange                  112935 non-null object
IncomeVerifiable             112935 non-null bool
StatedMonthlyIncome          112935 non-null float64
LoanOriginalAmount           112935 non-null int64
MonthlyLoanPayment           112935 non-null float64
PercentFunded                112935 non-null float64
Recommendations              112935 non-null int64
Investors                    112935 non-null int64
CreditRating                 112935 non-null object
dtypes: bool(2), float64(16), int64(5), object(10)
memory usage: 27.8+ MB

In [18]:
df_loan.CreditRating.unique()

array(['C', 'A', 'HR', 'D', 'B', 'E', 'AA', 'NC'], dtype=object)

In [19]:
df_loan.CreditRating.value_counts()

C     23745
B     19757
D     19323
A     17705
E     13005
HR    10425
AA     8834
NC      141
Name: CreditRating, dtype: int64

The "NC" rating is only used in the years prior to 2009, and the number of borrowers who received this rating is very low, we consider dropping them.

In [20]:
df_loan = df_loan[df_loan['CreditRating'] != 'NC']

In [21]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112794 entries, 0 to 113936
Data columns (total 33 columns):
ListingKey                   112794 non-null object
ListingCreationDate          112794 non-null object
CreditGrade                  28812 non-null object
Term                         112794 non-null int64
LoanStatus                   112794 non-null object
BorrowerAPR                  112770 non-null float64
BorrowerRate                 112794 non-null float64
ProsperRating (numeric)      83982 non-null float64
ProsperRating (Alpha)        83982 non-null object
ProsperScore                 83982 non-null float64
ListingCategory (numeric)    112794 non-null int64
BorrowerState                107333 non-null object
Occupation                   109307 non-null object
EmploymentStatus             110581 non-null object
IsBorrowerHomeowner          112794 non-null bool
CreditScoreRangeLower        112214 non-null float64
CreditScoreRangeUpper        112214 non-null float64
OpenCreditLines              105331 non-null float64
InquiriesLast6Months         112165 non-null float64
AmountDelinquent             105313 non-null float64
RevolvingCreditBalance       105331 non-null float64
BankcardUtilization          105331 non-null float64
AvailableBankcardCredit      105389 non-null float64
DebtToIncomeRatio            104394 non-null float64
IncomeRange                  112794 non-null object
IncomeVerifiable             112794 non-null bool
StatedMonthlyIncome          112794 non-null float64
LoanOriginalAmount           112794 non-null int64
MonthlyLoanPayment           112794 non-null float64
PercentFunded                112794 non-null float64
Recommendations              112794 non-null int64
Investors                    112794 non-null int64
CreditRating                 112794 non-null object
dtypes: bool(2), float64(16), int64(5), object(10)
memory usage: 27.8+ MB

In [22]:
df_loan.CreditRating.value_counts()

C     23745
B     19757
D     19323
A     17705
E     13005
HR    10425
AA     8834
Name: CreditRating, dtype: int64

In [23]:
conversion = {'AA': 7, 'A': 6, 'B': 5, 'C': 4, 'D': 3, 'E': 2, 'HR': 1}

In [24]:
## Create a variable to replace the original numeric credit rating 
df_loan['CreditRating_Numeric'] = df_loan.apply(lambda x: conversion[x.CreditRating], axis=1)

In [25]:
df_loan['CreditRating_Numeric'] = df_loan['CreditRating_Numeric'].astype(float)

In [26]:
df_loan.drop(['CreditGrade','ProsperRating (numeric)', 'ProsperRating (Alpha)'], axis = 1, inplace = True)

In [27]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112794 entries, 0 to 113936
Data columns (total 31 columns):
ListingKey                   112794 non-null object
ListingCreationDate          112794 non-null object
Term                         112794 non-null int64
LoanStatus                   112794 non-null object
BorrowerAPR                  112770 non-null float64
BorrowerRate                 112794 non-null float64
ProsperScore                 83982 non-null float64
ListingCategory (numeric)    112794 non-null int64
BorrowerState                107333 non-null object
Occupation                   109307 non-null object
EmploymentStatus             110581 non-null object
IsBorrowerHomeowner          112794 non-null bool
CreditScoreRangeLower        112214 non-null float64
CreditScoreRangeUpper        112214 non-null float64
OpenCreditLines              105331 non-null float64
InquiriesLast6Months         112165 non-null float64
AmountDelinquent             105313 non-null float64
RevolvingCreditBalance       105331 non-null float64
BankcardUtilization          105331 non-null float64
AvailableBankcardCredit      105389 non-null float64
DebtToIncomeRatio            104394 non-null float64
IncomeRange                  112794 non-null object
IncomeVerifiable             112794 non-null bool
StatedMonthlyIncome          112794 non-null float64
LoanOriginalAmount           112794 non-null int64
MonthlyLoanPayment           112794 non-null float64
PercentFunded                112794 non-null float64
Recommendations              112794 non-null int64
Investors                    112794 non-null int64
CreditRating                 112794 non-null object
CreditRating_Numeric         112794 non-null float64
dtypes: bool(2), float64(16), int64(5), object(8)
memory usage: 26.0+ MB

In [29]:
df_loan.rename(columns = {'ListingCategory (numeric)': 'ListingCategory_Numeric'}, inplace = True)

In [30]:
type_of_loan = {0: 'Not Available', 1: 'Debt Consolidation', 2: 'Home Improvement', 3: 'Business',
                4: 'Personal Loan', 5: 'Student Use', 6: 'Auto', 7: 'Other',
                8: 'Baby&Adoption', 9: 'Boat', 10: 'Cosmetic Procedure', 11: 'Engagement Ring',
                12: 'Green Loans', 13: 'Household Expenses', 14: 'Large Purchases', 15: 'Medical/Dental',
                16: 'Motorcycle', 17: 'RV', 18: 'Taxes', 19: 'Vacation', 20: 'Wedding Loans'}

In [31]:
## Create a text listing category variable for visualization purpose
df_loan['ListingCategory'] = df_loan.apply(lambda x: type_of_loan[x.ListingCategory_Numeric], axis=1)

In [33]:
df_loan.ListingCategory.value_counts()

Debt Consolidation    57558
Not Available         16824
Other                 10424
Home Improvement       7377
Business               7140
Auto                   2561
Personal Loan          2395
Household Expenses     1987
Medical/Dental         1507
Taxes                   882
Large Purchases         863
Vacation                764
Wedding Loans           762
Student Use             750
Motorcycle              304
Engagement Ring         214
Baby&Adoption           196
Cosmetic Procedure       91
Boat                     85
Green Loans              58
RV                       52
Name: ListingCategory, dtype: int64

In [38]:
df_loan['ListingCreationDate'] = pd.to_datetime(df_loan['ListingCreationDate'])

In [39]:
df_loan.head()

,ListingKey,ListingCreationDate,Term,LoanStatus,BorrowerAPR,BorrowerRate,ProsperScore,ListingCategory_Numeric,BorrowerState,Occupation,...,IncomeVerifiable,StatedMonthlyIncome,LoanOriginalAmount,MonthlyLoanPayment,PercentFunded,Recommendations,Investors,CreditRating,CreditRating_Numeric,ListingCategory
0,1021339766868145413AB3B,2007-08-26 19:09:29.263,36,Completed,0.16516,0.1580,NaN,0,CO,Other,...,True,3083.333333,9425,330.43,1.0,0,258,C,4.0,Not Available
1,10273602499503308B223C1,2014-02-27 08:28:07.900,36,Current,0.12016,0.0920,7.0,2,CO,Professional,...,True,6125.000000,10000,318.93,1.0,0,1,A,6.0,Home Improvement
2,0EE9337825851032864889A,2007-01-05 15:00:47.090,36,Completed,0.28269,0.2750,NaN,0,GA,Other,...,True,2083.333333,3001,123.32,1.0,0,41,HR,1.0,Not Available
3,0EF5356002482715299901A,2012-10-22 11:02:35.010,36,Current,0.12528,0.0974,9.0,16,GA,Skilled Labor,...,True,2875.000000,10000,321.45,1.0,0,158,A,6.0,Motorcycle
4,0F023589499656230C5E3E2,2013-09-14 18:38:39.097,36,Current,0.24614,0.2085,4.0,2,MN,Executive,...,True,9583.333333,15000,563.97,1.0,0,20,D,3.0,Home Improvement

In [37]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112794 entries, 0 to 113936
Data columns (total 32 columns):
ListingKey                 112794 non-null object
ListingCreationDate        112794 non-null datetime64[ns]
Term                       112794 non-null int64
LoanStatus                 112794 non-null object
BorrowerAPR                112770 non-null float64
BorrowerRate               112794 non-null float64
ProsperScore               83982 non-null float64
ListingCategory_Numeric    112794 non-null int64
BorrowerState              107333 non-null object
Occupation                 109307 non-null object
EmploymentStatus           110581 non-null object
IsBorrowerHomeowner        112794 non-null bool
CreditScoreRangeLower      112214 non-null float64
CreditScoreRangeUpper      112214 non-null float64
OpenCreditLines            105331 non-null float64
InquiriesLast6Months       112165 non-null float64
AmountDelinquent           105313 non-null float64
RevolvingCreditBalance     105331 non-null float64
BankcardUtilization        105331 non-null float64
AvailableBankcardCredit    105389 non-null float64
DebtToIncomeRatio          104394 non-null float64
IncomeRange                112794 non-null object
IncomeVerifiable           112794 non-null bool
StatedMonthlyIncome        112794 non-null float64
LoanOriginalAmount         112794 non-null int64
MonthlyLoanPayment         112794 non-null float64
PercentFunded              112794 non-null float64
Recommendations            112794 non-null int64
Investors                  112794 non-null int64
CreditRating               112794 non-null object
CreditRating_Numeric       112794 non-null float64
ListingCategory            112794 non-null object
dtypes: bool(2), datetime64[ns](1), float64(16), int64(5), object(8)
memory usage: 26.9+ MB

## Export the data to csv for Tableau Explanatory Analysis

In [40]:
df_loan.to_csv('LoanListingCleaned.csv')